step1
lehdqlsl/java-todo-list pull request #40
Opened 2023-11-29 01:49 UTC by jun3442

## 🔥 ㅤPR Contents
1,2주차 요구사항 구현
(2주차 4번 예외 처리 못한게 있어서 마저 수정하겠습니다)

## 🛠ㅤChanges
-

## 🙋ㅤComments (optional)
-

2023-11-29 07:41 UTC, jun3442 commented
2주차에서 기능별로 커밋해보겠습니다.

2023-12-01 03:18 UTC, lehdqlsl requested changes
몇 가지 코멘트 남겼는데 확인 부탁드려요~

그리고 기존 TodoList를 TodoItem을 관리하는 TodoManager 클래스로 변경하고,
아래 항목에 맞게 클래스를 분리해주세요~

TodoManager: 할 일의 관리 (추가, 삭제, 조회)와 관련된 비즈니스 로직 담당
TodoUI: 사용자 인터페이스 로직을 담당, 이 클래스에서는 사용자로부터 입력을 받고, 결과를 출력함
Main: 프로그램의 실행을 담당하는 메인 클래스

2023-12-01 03:18 UTC, lehdqlsl commented on src/main/java/org/homework/Main.java
> +        boolean run = true;
boolean형 변수명은 아래 글을 한번 참고해보고 바꿔주세요~

https://soojin.ro/blog/naming-boolean-variables

2023-12-01 03:18 UTC, lehdqlsl commented on src/main/java/org/homework/Main.java
> +                num = scanner.nextInt();
지난번 멘토링에서 Enum을 다뤘었는데, 함께 적용해보세요~

2023-12-01 03:18 UTC, lehdqlsl commented on src/main/java/org/homework/TodoItem.java
> +}
객체 표현 👍

2024-02-13 02:37 UTC, closed without merging