Step4
lehdqlsl/java-todo-list pull request #74
Opened 2024-07-31 00:03 UTC by ekd594ff

## 🔥 ㅤPR Contents
- DB 사용(mysql, JDBC)
- Repository interface 를 통해 기존 Hashmap 기반 Repository 와 실제 DB repository 이동 가능
## 🛠ㅤChanges
- 설정은 application.properties.example 파일을 수정 한 뒤 파일명에서 '.example' 을 제거하여 사용합니다 
```bash
app.mode= # development, production
db.url= # url of database server
db.username= # database username
db.password= # database password
db.name= # database(mysql)
db.poolsize= # the number of pool connection
```
## 🙋ㅤComments (optional)
-

2024-08-02 03:32 UTC, lehdqlsl requested changes
마지막 단계도 잘 해주셨습니다 👍 
거의 다 왔으니 조금만 수정해주세요~

2024-08-02 03:32 UTC, lehdqlsl commented on src/main/java/org/homework/step4/Main.java
> +        }
설정을 이용한 Repository 분리 👍 

위 로직을 한번 **정적 팩토리 메서드 패턴** 으로 변경해보실까요?
크게 어려운 개념이 아니기 때문에 금방 적용하실 수 있을겁니다.

2024-08-02 03:32 UTC, lehdqlsl commented on src/main/java/org/homework/step4/controller/TodoController.java
> +            case SEARCH:
한줄로 코드를 작성하면 간결해 보이긴 하지만, 가독성이 매우 떨어집니다.
변수가 주는 코드의 가독성이 이점이 있기 때문인데요.
의미 있는 변수를 받아서 파라미터에 넘기도록 수정해보세요~

2024-08-02 03:32 UTC, lehdqlsl commented on src/main/java/org/homework/step4/entity/Todo.java
> +    }
해당 코드는 MySQLTodoRepository에 위치하는게 더 맞습니다.

2024-08-02 03:32 UTC, lehdqlsl commented on src/main/java/org/homework/step4/view/InputView.java
> +    }
같은 코드가 너무 반복된다면 메소드로 묶어도 좋습니다.

```suggestion
    public int getUpdatedTodoId() {
        System.out.print("수정할 ID: ");
        
        // while 단위로 메소드로 묶어도 좋고
        while (true) {
           // parse 부분만 묶어도 좋습니다.
            try {
                return Integer.parseInt(this.getLine());
            } catch (NumberFormatException e) {
                System.out.println("올바른 ID를 입력해 주세요");
            }
        }
    }
```

2024-08-03 08:52 UTC, ekd594ff commented
## 🔥 ㅤPR Contents
-

## 🛠ㅤChanges
- 정적 팩토리 메서드 패턴을 구현하였습니다
- Controller 내부의 리턴값을 유의미한 변수로 전달하였습니다
- ResultSet 을 변환하는 메소드를 MySQLTodoRepository로 이동하였습니다
- 내부의 코드가 동일한 여러 메소드를 하나로 통합하였습니다 
## 🙋ㅤComments (optional)
- 정적 팩토리 메소드 구현이 잘 되었는지 모르겠습니다 커넥션 풀과 MySQLTodoRepository, MapTodoRepository 까지 
생성자가 아닌 메소드로 생성해야 할지 잘 모르겠습니다
- 제 경우에는 Repository 인터페이스 내부에 팩토리 메서드를 구현하였는데 맞는 방식인지 모르겠습니다

2024-08-03 10:36 UTC, lehdqlsl commented
@ekd594ff 나머지 부분은 잘 해주셨습니다~
코드나 질문으로 봤을 때, 정적 팩토리 메소드 패턴은 너무 간단하게 공부하신거 같습니다. 
아래 링크로 한번 더 공부해보시고 수정 부탁드릴게요.
https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90

2024-08-04 07:14 UTC, ekd594ff commented
## 🔥 ㅤPR Contents
-
## 🛠ㅤChanges
- PoolConnection, Respository에 정적 팩토리 메서드 패턴을 적용하였습니다
- 싱글톤 패턴을 적용하였습니다
## 🙋ㅤComments (optional)
- 정적 팩토리 메소드 네이밍 컨벤션이 있음을 처음 알았습니다

2024-08-05 12:19 UTC, lehdqlsl approved these changes
머지하겠습니다. 마지막까지 고생 많으셨습니다. 👍

2024-08-05 12:19 UTC, lehdqlsl commented on src/main/java/org/homework/step4/jdbc/JDBCConnectionPool.java
> +                connection.close();
싱글톤으로 구현 잘 하셨습니다. 👍 
실제로 옛날에는 이러한 db 커넥션은 싱글톤으로 구현하여 관리했습니다.

첨언 하자면, spring boot도 마찬가지로 DataSource 객체에 빈으로 등록되어 싱글톤으로 관리가 됩니다.
+ spring Boot 2.0 이상에서는 기본 커넥션 풀로 HikariCP를 사용하고 있다는 점. 알아두시면 좋습니다~

2024-08-05 12:20 UTC, merged